baseurl: ""
url: "https://dtzxporter.com"

title: DTZxPorter
description: "Software Engineer, Reverse Engineer, Problem Solver."
avatar: assets/avatar.png
favicon: assets/favicon.png

header_text: "Software Engineer, Reverse Engineer, Problem Solver."
header_feature_image: assets/banner.jpeg
header_feature_image_responsive: true
footer_text: >
  Copyright © 2025 DTZxPorter. All Rights Reserved.

excerpt: true
post_navigation: true
color_image: /assets/img/lineart.png

katex: false
mermaid:
google_analytics:
cookie_consent: false
color_theme: dark

comments:
  disqus_shortname:
  cusdis_app_id:
  utterances:
    repo:
    issue-term:

paginate: 5
paginate_path: "/blog/page:num"

collections:
  tools:
    output: true
    permalink: /:collection/:name

sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude:
  [
    ".jekyll-cache",
    ".jekyll-metadata",
    ".idea",
    "vendor/*",
    "assets/node_modules/*",
  ]

markdown: kramdown

remote_theme: sylhare/Type-on-Strap@v2.4.7
